### ISSUE TITLE
count() fails with an exception

### ISSUE THREAD

**Issue by g6g8** [russellmcdonell/pySFeel#1]
Hello Russell,
First a great thank you for writing this module, I'm using it extensively to remove business logic from some of our programs and moving it into DMNs where the business has the freedom to control as they wish.

I have been diving into DMNrules and SFeel for a few weeks now and today, as I decided to improve my knowledge on SFeel expressions I have found a few "bugs".

The first concerns the count() function which actually crashes with a Python exception.

The cause is on this line:
https://github.com/russellmcdonell/pySFeel/blob/28013c09c44c1cc00dc8d170b0b6cd6bd8855364/pySFeel/SFeel.py#L1390

Which sould read p.expr and not p.expr0.
Do you prefer I make pull requests ?

Thanks a million,
Gabriel.

**Comment by russellmcdonell** [comment]
Thanks Gabriel. Strangely I've been looking at pySFeel recently - thought I
should add in the new DMN 2.0 Built-in functions. But I started by building
some unit tests with pytest and like you, found a bug. "in" a list of
ranges didn't return true when the value was in one of the ranges. I fixed
that. I'll complete the unit test suite, add your fixes and release a new
version before I add in the DMN 2.0 functions.

Russell McDonell

**Comment by russellmcdonell** [comment]
Oops - that should be DMN 1.3 ...

**Comment by russellmcdonell** [comment]
Fixed in the next release - see the new 'VERSIONS.md' file. Gabriel, I'd like to acknowledge your contribution. At the moment I'm using 'Gabriel (g6g8)'. Is that O.K.? Happy to put in your full name/link(s) etc. Just let me know.

**Comment by g6g8** [comment]
Hello Russell,
Wow that was fast, thanks a lot for your rapidity.
I will open another issue with number().
Thanks for the correction on the DMN version number, I was trying to find what DMN 2.0 was ...
My full name is Gabriel Galibourg, I'll "enrich" my github profile - no problem using the link to my profile.

**Comment by russellmcdonell** [comment]
Fixed in v1.1.11

**Comment by russellmcdonell** [comment]
Gabriel, I've done a new release and uploaded it to PyPI. The changes are
documented in a file called VERSIONS.md in github.

Now I suspect that there's another bug - adding or subtracting a period
from a date or datetime, where the period is in days. The documentation
suggests that that would be adding/subtracting a float from a date/datetime
which won't work. I will need to convert the data to a datetime.timedelta
first.

So there may be another release before I get onto the DMN 1.3 upgrade. And
I start a new job on Monday, so time may get a little scarcer.


Russell McDonell

**Comment by russellmcdonell** [comment]
I've just release version 1.2.0 of pySFeel and version 1.2.0 of pyDMNrules. Both have bug fixes. I've uploaded a complex rules set (AN-SNAP rules (DMN).xlsx) to pyDMNrules on github. That forced me to fix lots of things like in() and valid values rules. I've also created unit test for both pySFeel and pyDMNrules so that I can do regression testing.
