### ISSUE TITLE
Problem on filter [item = xx]

### ISSUE THREAD

**Issue by g6g8** [russellmcdonell/pySFeel#2]
[1,2,3,4][item = 1]
returns None
when it should return [1.0]

I believe the fix is located in:
https://github.com/russellmcdonell/pySFeel/blob/28013c09c44c1cc00dc8d170b0b6cd6bd8855364/pySFeel/SFeel.py#L461
which should read
        return (p.EQUALS, p.expr)

**Comment by russellmcdonell** [comment]
Fixed in next release

**Comment by russellmcdonell** [comment]
Fixed in v1.1.11
