### ISSUE TITLE
Filter does not return the filtered list but instead a list containing the filter value

### ISSUE THREAD

**Issue by g6g8** [russellmcdonell/pySFeel#3]
if you evaluate:
[1,2,3,4][item > 1]
it should return [2.0, 3.0, 4.0]
but it returns [1.0, 1.0, 1.0]

The fix is located in lines 496-512
Where the (6) lines:
                                retList.append(value)
should read
                                retList.append(p.expr[i])

**Comment by russellmcdonell** [comment]
Fixed in the next release

**Comment by russellmcdonell** [comment]
Fixed in v1.1.11
