### ISSUE TITLE
all(true,false) should return false ? should it not ?

### ISSUE THREAD

**Issue by g6g8** [russellmcdonell/pySFeel#4]
I'm not sure about this one as finding, understandable, DMN/SFeel documentation proves to be difficult.
My understanding is that all() should evaluate to true if and only if all elements are true. Therefore:
all(true,false) should return false.
it currently returns true.

If my understanding is correct then the fix is located in lines 1500-1528.
In fact the method allFunc() is defined twice, once in line 1500 and again in lines 1528. The definition in lines 1528 is wrong and should be deleted, leaving the one in 1500 which is correct.

**Comment by russellmcdonell** [comment]
Fixed in next release. Also all() and any() wheren't handling 'null' correctly. This is also fixed.

**Comment by russellmcdonell** [comment]
fixed in v1.1.11
