### ISSUE TITLE
number(null,...) fails with a Python exception.

### ISSUE THREAD

**Issue by g6g8** [russellmcdonell/pySFeel#5]
In itself its not a problem except when pyDMNRules loads the rules spreadsheet, as it evaluates each cell it supplies the glossary variables with the null values. Thus one finds himself with number(null,...) which crashes the loading of the rules.

I would suggest changing the numberfunc as follows:
    @_("NUMBERFUNC expr COMMA expr COMMA expr RPAREN")
    def expr(self, p):
        """ Float from formatted string"""
        number = p.expr0
        if isinstance(number, float):
            return number # that's pretty obvious!
        if not isinstance(number, str):
            return None

        grouping = p.expr1

But I'm sure there are other ways to do the same, more than one way to skin a cat ...

**Comment by russellmcdonell** [comment]
The argument to number() must be strings.
10.3.2.16 Error Handling
When a built-in function encounters input that is outside its defined domain, the function SHOULD report or log
diagnostic information if appropriate, and SHALL return null.

So returning 'number' when you are passed a float is actually wrong.
Will check that 'number' is a string and return None if it is not.
And check that grouping and decimal are either a string or a null and return None if they are not.

**Comment by russellmcdonell** [comment]
Fixed in v1.1.11
